name: Test module

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    uses: ./.github/workflows/reusable-test.yml

  test:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - shell: python
        run: |
          import sys
          if all(result == "success" for result in ${{ toJSON(needs.*.result) }}):
            sys.exit(0)
          else:
            sys.exit(1)
